import { useEffect, useState } from "react";
import Head from "next/head";

import { Breadcrumb, Button, Card, Col, Layout, notification, Row } from "antd";

import CustomerFormModal from "../../../components/customers/CustomersFormModal";
import CustomersTable from "../../../components/customers/CustomersTable";
import { Customer } from "../../../components/customers/types";
import {
  createCustomer,
  updateCustomer,
  getCustomers,
  removeCustomer,
} from "../../../services/customers";

export default function Index() {
  const [isModalVisible, setIsModalVisible] = useState<boolean>(false);
  const [customer, setCustomer] = useState<Customer | null>(null);
  const [customers, setCustomers] = useState([]);
  const [lockSave, setLockSave] = useState(false);

  const [tableIsLoading, setTableIsLoading] = useState<boolean>(false);

  /**
   * Get customers from data store.
   */
  const fetchCustomers = () => {
    setTableIsLoading(true);
    getCustomers()
      .then((data) => {
        setCustomers(data);
      })
      .catch(() => {
        notification.error({
          message: "Error while getting the customers",
        });
      })
      .finally(() => {
        setTableIsLoading(false);
      });
  };

  const onEdit = (customer: Customer) => {
    setCustomer(customer);
    setIsModalVisible(true);
  };

  const onDelete = (id: any) => {
    removeCustomer(id)
      .then(() => {
        notification.success({
          message: "Customer Removed",
        });
        fetchCustomers();
      })
      .catch(() => {
        notification.error({
          message: "Error while removing the customer",
        });
      });
  };

  /**
   * Create new customer
   * @param newCustomer
   */
  const addNewCustomer = (newCustomer: any) => {
    setLockSave(true);
    createCustomer(newCustomer)
      .then((response) => {
        if (response) {
          notification.success({
            message: "Customer Created",
          });
          fetchCustomers();
          setIsModalVisible(false);
        }
      })
      .catch(() => {
        notification.error({
          message: "Error while creating the customers",
        });
      })
      .finally(() => {
        setLockSave(false);
      });
  };

  /**
   * Create new customer
   * @param newCustomer
   */
  const modifyCustomer = (newCustomer: any) => {
    setLockSave(true);
    updateCustomer(newCustomer)
      .then((response) => {
        if (response) {
          notification.success({
            message: "Customer Updated",
          });
          fetchCustomers();
          setCustomer(null);
          setIsModalVisible(false);
        }
      })
      .catch(() => {
        notification.error({
          message: "Error while creating the customers",
        });
      })
      .finally(() => {
        setLockSave(false);
      });
  };

  const handleOk = (newCustomer: any) => {
    console.log(newCustomer);
    if (newCustomer.key) {
      modifyCustomer(newCustomer);
    } else {
      addNewCustomer(newCustomer);
    }
  };

  useEffect(() => {
    fetchCustomers();
  }, []);

  return (
    <>
      <Head>
        <title>Clientify | Customers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb style={{ margin: "16px 0" }}>
        <Breadcrumb.Item>Clientify</Breadcrumb.Item>
        <Breadcrumb.Item>Customers</Breadcrumb.Item>
      </Breadcrumb>
      <Layout>
        <Row>
          <Col span={24}>
            <Card
              title="List of customers"
              extra={
                <Button
                  onClick={() => {
                    setIsModalVisible(true);
                  }}
                  type="primary"
                >
                  New Customer
                </Button>
              }
            >
              <CustomersTable
                customers={customers}
                loading={tableIsLoading}
                onEdit={onEdit}
                onDelete={onDelete}
              />
              <CustomerFormModal
                lockSave={lockSave}
                customer={customer}
                isModalVisible={isModalVisible}
                handleOk={handleOk}
                handleCancel={() => {
                  setIsModalVisible(false);
                  setCustomer(null);
                }}
              />
            </Card>
          </Col>
        </Row>
      </Layout>
    </>
  );
}
