import { Breadcrumb } from "antd";
import Head from "next/head";

export default function AdminLayout() {
  return (
    <>
      <Head>
        <title>Clientify | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb style={{ margin: "16px 0" }}>
        <Breadcrumb.Item>Clientify</Breadcrumb.Item>
        <Breadcrumb.Item>Dashboard</Breadcrumb.Item>
      </Breadcrumb>
      <div>Dashboard page</div>
    </>
  );
}
